### PR TITLE
make it clear how to initiate selectize

### PR DESCRIPTION
**Pull request by KristerV**

### CODE REVIEW

**Comment by jshimko** [comment]
You don't actually need those options to be explicitly set for the plugin to work (every site I currently use it on works fine without it).  Those are optional Selectize options.

**Comment by KristerV** [comment]
strange. wonder why I had to use "create" to get it working at all.

**Comment by jshimko** [comment]
I definitely should put together a sample repo though.  I think it'd probably be helpful for a lot of people to have something to test out or copy/paste into their own app.  

On my to-do list.  ;)

**Comment by jshimko** [comment]
Oh wait... try leaving out that `selectizeOptions: {}` altogether in the schema definition.  Just realizing I don't have that in any of my schemas for my Seletize inputs.  Maybe the empty object was breaking the default Selectize settings.

**Comment by jshimko** [comment]
For example, I have a schema like this:

``` js
users: {
  type: [String],
  autoform: {
    options: function () {
      return Meteor.users.find().map(function (user) {
        return {
          value: user._id,
          label: user.username
        }
      });
    }
  }
}
```

and then the input looks like this:

``` html
{{> afFieldInput name='users' type="selectize" multiple=true }}
```

**Pull request closed without merging**
